### kosis 부산광역시 가스공급량 2010-2020
- 년도별 도시가스/프로판 판매량 비율
  프로판 가스보다 도시가스 사용량이 점점 늘어나는가

- 년도별 도시가스, 년도별 프로판 사용량 상관도
  도시가스 사용량이 점점 많아지고 있는가
  프로판 가스 사용량은 점점 줄어들고 있는가

- 도시가스
	년도별 겨울(10, 11, 12, 1, 2, 3) 평균사용량/
	비겨울(4, 5, 6, 7, 8, 9) 평균사용량
	--> test (평균 사용량에 차이가 있는가.) 

### 같은 분석을, 프로판/부탄 가스를 대상으로 실행.

In [2]:
import numpy as np
import math
import pickle
import matplotlib.pyplot as plt
from scipy import stats

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def split_len(data_list):
    len_list=[]
    for e in data_list:
        len_list.append(len(e))
    #print(set(len_list))
    if len(set(len_list))>1:
        for i in set(len_list):
            print(i, len_list.count(i))
    return set(len_list)

def dist_np(p1, p2): #  [3,10]  [5,25]
    return math.sqrt(sum((p2-p1)**2))

def process_product_names(s):
    r = []
    remove_after = ['(', ' 외', ' 외']
    split_at = ['+', ',']
    for c in remove_after:
        if c in s:
            s = s[:s.index(c)]
        
    for c in split_at:
        if c in s:
            r = r + s.split(c)
            
    if len(r) == 0:
        r.append(s)
    
    return r

# sample1 = 'productA+productB'
# sample2 = 'productA,productB'
# sample3 = 'product(A+B)'
# sample4 = 'product 외 abc'
# sample5 = 'product'

# print(process_product_names(sample1)) #['productA', 'productB']
# print(process_product_names(sample2))
# print(process_product_names(sample3))
# print(process_product_names(sample4))
# print(process_product_names(sample5))

In [3]:
np.set_printoptions(precision=5, suppress=True)

raw_data=[]
with open ('가스공급량_20230217170926.csv') as f:
    for line in f:
          raw_data.append(line[:-1].split(','))
t = set()            
for e in raw_data:
    t.add(len(e))
print(t)

np_data = np.array(raw_data[2:])
np_data = np_data[:, 2:].astype(np.int64)
print(np_data[:3])

{8}
[[     1 179086    311   8775     64  26227]
 [     1 139496    311   8745     64  23518]
 [     1 143581    311   8092     64  23959]]


In [46]:
by_year = np.add.redu

(0, '"시점"')
(1, '"월별(1)"')
(2, '판매소수 (개)')
(3, '판매량')
(4, '판매소수 (개)')
(5, '판매량')
(6, '판매소수 (개)')
(7, '판매량')
