In [2]:
# python list

lista = []
print(lista)

lista.append('a')
print(lista)

[]
['a']


In [11]:
# numpy ndarray
import numpy as np

#ndarray는 데이터 추가제거는 어렵고 주어진 데이터를 사용해서 계산을 쉽게하는 목적이다.
array1 = np.array(lista)
array2 = np.array([1,2,3,4])
array3 = np.array([x for x in range(5)])

# array1.append('c')
# print(array1)

print(array1, type(array1))
print(array3)
print(array3[1:4])
print(array3[[1,4]])
print(array3[array3%2==0])
print(array3[array3>2])


['a'] <class 'numpy.ndarray'>
[0 1 2 3 4]
[1 2 3]
[1 4]
[0 2 4]
[3 4]


In [15]:
# for, if
# for i in array3:
#     print(i)
    
for i in range(5):
    if i > 2:
        print(i)
        
print(array3[array3>2])

3
4
[3 4]


In [21]:
# function

def function_name(n):
    return n*10
    
return_value = function_name(10)
print('return_value:', return_value)

assert function_name(100)==1001

return_value: 100


AssertionError: 

In [45]:
import random

random.seed(123)

listb = []
for i in range(10):
    listb.append(random.randint(0, 100))
    
for i in listb:
    if i >50:
        print(i)
        
        
listb_np = np.array(listb)
print(listb_np[listb_np>50])
print(len(listb_np[listb_np>50]))

# _는 사용하지 않는 변수를 대신할 때 사용한다.
listc = [random.randint(0, 100) for _ in range(10)]
print(listc)


98
52
68
[98 52 68]
3
[71, 42, 43, 6, 20, 17, 43, 71, 42, 89]
