In [1]:
import numpy as np
import math
import pickle

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def split_len(data_list):
    len_list=[]
    for e in data_list:
        len_list.append(len(e))
    #print(set(len_list))
    if len(set(len_list))>1:
        for i in set(len_list):
            print(i, len_list.count(i))
    return set(len_list)

def dist_np(p1, p2): #  [3,10]  [5,25]
    return math.sqrt(sum((p2-p1)**2))

def process_product_names(s):
    r = []
    remove_after = ['(', ' 외', ' 외']
    split_at = ['+', ',']
    for c in remove_after:
        if c in s:
            s = s[:s.index(c)]
        
    for c in split_at:
        if c in s:
            r = r + s.split(c)
            
    if len(r) == 0:
        r.append(s)
    
    return r

# sample1 = 'productA+productB'
# sample2 = 'productA,productB'
# sample3 = 'product(A+B)'
# sample4 = 'product 외 abc'
# sample5 = 'product'

# print(process_product_names(sample1)) #['productA', 'productB']
# print(process_product_names(sample2))
# print(process_product_names(sample3))
# print(process_product_names(sample4))
# print(process_product_names(sample5))

In [2]:
csv_data = []
with open ('전국육교정보표준데이터.csv') as f:
    for line in f:
          csv_data.append(my_split(line[:-1]))

print(len(split_len(csv_data)))



for e in enumerate(csv_data[0]):
    print(e)

1
(0, '육교명')
(1, '도로종류')
(2, '도로노선번호')
(3, '도로노선명')
(4, '소재지도로명주소')
(5, '위도')
(6, '경도')
(7, '육교연장')
(8, '육교높이')
(9, '허용통행하중')
(10, '통행제한높이')
(11, '육교폭')
(12, '난간높이')
(13, '조명개수')
(14, '장애인편의시설설치여부')
(15, '장애인편의시설종류')
(16, '장애인편의시설수량')
(17, '부대시설종류')
(18, '부대시설수량')
(19, '육교준공일자')
(20, '내진설계적용여부')
(21, '안전등급')
(22, '사용제한구분')
(23, '육교보수보강내역')
(24, '최종안전점검유형')
(25, '최종안전점검일자')
(26, '관리기관명')
(27, '데이터기준일자')
(28, '제공기관코드')
(29, '제공기관명')


In [24]:
np_data = np.array(csv_data)

np_data = np_data[:, :22]
print(np_data[:7])

[['육교명' '도로종류' '도로노선번호' '도로노선명' '소재지도로명주소' '위도' '경도' '육교연장' '육교높이'
  '허용통행하중' '통행제한높이' '육교폭' '난간높이' '조명개수' '장애인편의시설설치여부' '장애인편의시설종류'
  '장애인편의시설수량' '부대시설종류' '부대시설수량' '육교준공일자' '내진설계적용여부' '안전등급']
 ['우신초교 앞 보도육교' '시도' '147' '신길로' '서울특별시 영등포구 신길로 190' '37.509263'
  '126.910801' '23' '4.7' '' '4.5' '3.4' '1' '8' 'Y' '점자블록+핸드레일 촉지판' '24'
  '' '' '1980-09-18' ' ' '보통']
 ['영등포역 횡단 보도육교' '기타' '없음' '경인선' '서울특별시 영등포구 경인로94길 7' '37.513895'
  '126.903695' '83' '' '0.5' '5.6' '3.2' '1.8' '14' 'Y' '엘리베이터' '' '' ''
  '1974-12-01' ' ' '보통']
 ['문래 보도육교' '시도' '245' '서부간선도로' '서울특별시 영등포구 문래로4길 4' '37.520246'
  '126.882018' '40' '5.1' '0.5' '4.5' '4' '1.2' '' 'Y' '엘리베이터' '' '' ''
  '2006-06-30' 'Y' '양호']
 ['양평1 보도육교' '시도' '245' '서부간선도로' '서울특별시 영등포구 양산로 3' '37.526193'
  '126.883081' '43' '5.7' '0.5' '4.5' '4' '1.2' '' 'Y' '엘리베이터' '' '' ''
  '2006-06-30' 'Y' '양호']
 ['양평2 보도육교' '시도' '245' '서부간선도로' '서울특별시 영등포구 양평로21길 26' '37.533447'
  '126.891821' '45' '5.7' '0.34' '4.5' '4' '1.2' '' 'Y' '엘리베이터' '' '' ''
  '2006

In [26]:
name = np_data[1:, 0]
length = np_data[1:, 7]
hight = np_data[1:, 10]
weight = np_data[1:, 9]
eqb = np_data[1:, 20]
sl = np_data[1:, 21]
year = np_data[1:, 19]
help = np_data[1:, 14]



print(name[:3])
print(length[:3])
print(hight[:3])
print(weight[:3])
print(sl[:3])
print(year[:3])
print(help[:3])

#print(np.unique(btypes, return_counts=True))
# btype_name, btype_count = np.unique(btypes, return_counts=True)
# print(btype_name)
# print(btype_count)
# print(btype_count*100 / sum(btype_count))

['우신초교 앞 보도육교' '영등포역 횡단 보도육교' '문래 보도육교']
['23' '83' '40']
['4.5' '5.6' '4.5']
['' '0.5' '0.5']
['보통' '보통' '양호']
['1980-09-18' '1974-12-01' '2006-06-30']
['Y' 'Y' 'Y']


In [30]:
#내진설계된 육교 비율
eqb = np_data[1:, 20]
eqb_name, eqb_count = np.unique(eqb, return_counts=True)
print(eqb_name)
print(eqb_count)
print(eqb_count*100 / sum(eqb_count))

[' ' 'N' 'Y']
[357 695 166]
[29.31034483 57.06075534 13.62889984]


In [31]:
#안전등급별 육교 개수, 비율
sl = np_data[1:, 21]
sl_name, sl_count = np.unique(sl, return_counts=True)
print(sl_name)
print(sl_count)
print(sl_count*100 / sum(sl_count))

['미흡' '보통' '불량' '양호' '우수']
[ 25 390   1 795   7]
[ 2.05254516 32.01970443  0.08210181 65.27093596  0.57471264]


In [49]:
#육교 길이
length = np_data[1:, 7]
#print(length)
len_list = []

for i in length:
    len_list.append(i)

print(len_list)


['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '10', '10', '100', '100', '103', '104', '104', '104.5', '104.6', '105', '105', '105', '105', '105', '105.1', '107', '108', '108', '108', '109', '109', '109.2', '11', '110', '110', '110.6', '111', '111', '112', '113', '115', '116', '116', '118', '118', '118.6', '119.3', '12', '12.2', '120', '121', '121.5', '122', '124', '125', '125', '125.9', '126', '126', '126.8', '129.3', '13.3', '13.58', '13.6', '130', '130', '130', '130', '130.0', '131', '132', '132', '133.2', '134.6', '137.1', '137.1', '138', '138.3', '138.3', '14', '14.5', '140', '142', '146', '15', '15', '15', '15', '15.6', '150', '150', '150', '150', '152', '155.4', '158', '158', '16', '16', '16', '16', '16', '16', '16.0', '16.5', '16.6', '16.6', '160', '160', '163.2', '164.6', '166', '166.6', '17', '17', '17', '17', '1

In [ ]:
# 내진설계 된 육교 퍼센트  eqb
# 안전등급별 육교 개수, 비율 sl
# 육교가 만들어진 연도 vs 장애인편의시설 간 상관관계 year
# (연도별 장애인 편의시설 갖춘 육교의 개수/ 해당연도 건설 육교 개수)

# 길이가 가장 긴 육교(육교연장)
# 가장 튼튼한 육교(허용통행하중)
# 가장 높은 육교(통행제한 높이)

# 육교연장, 허용통행하중, 통행제한 높이에 대해
# 최대, 최소값, 평균, 표준편차